#!/bin/sh

#
# Spark on K finalize script
#

#
# K Job system forcibly exports POSIXY_CORRECT, so unset it.
#
unset POSIXLY_CORRECT

SPARK_HOME=`pwd`/../spark-1.6.0-bin-custom-spark
SPARK_HOME=`(cd ${SPARK_HOME}; pwd)`

rankdir=`pwd`
common_dir=`(cd ..; pwd)`

mpiexec /work/system/bin/msh /bin/bash ${common_dir}/stop-slave.sh

SPARK_CONF_DIR=${COMMON_DIR}/conf \
SPARK_LOCAL_DIRS=${rankdir}/localdir \
SPARK_WORKER_DIR=${rankdir}/work \
SPARK_LOG_DIR=${rankdir}/logs \
SPARK_PID_DIR=${rankdir}/pids \
${SPARK_HOME}/sbin/stop-master.sh
