#!/bin/sh

#
# Spark on K finalize script
#

curdir=`pwd`
# move to the home directory
cd ${PJM_JOBDIR}

#
# K Job system forcibly exports POSIXY_CORRECT, so unset it.
#
unset POSIXLY_CORRECT

rankdir=`pwd`
if [ -z "${COMMON_DIR}" ]; then
    COMMON_DIR=`(cd ..; pwd)`
    if [ "0" == "`basename ${rankdir}`" ]; then
        COMMON_DIR=`(cd ..; pwd)`
    else
        COMMON_DIR=`pwd`
    fi
fi

${SPARK_K}spark-k-wait-spark-job-finish --host ${K_MASTER_NODE}

mpiexec /work/system/bin/msh ${COMMON_DIR}/stop-spark.sh

cd ${curdir}
