#!/bin/sh

#
# Spark on K finalize script
#

curdir=`pwd`
# move to the home directory
cd

#
# K Job system forcibly exports POSIXY_CORRECT, so unset it.
#
unset POSIXLY_CORRECT

rankdir=`pwd`
common_dir=`(cd ..; pwd)`
if [ "0" == "`basename ${HOME}`" ]; then
    common_dir=`(cd ..; pwd)`
else
    common_dir=`pwd`
fi

${SPARK_K}spark-k-wait-spark-job-finish --host ${K_MASTER_NODE}

mpiexec /work/system/bin/msh ${common_dir}/stop-spark.sh

cd ${curdir}
